export const environment = {
  production: false,
  userServiceApi: 'http://localhost:5001/api/v1',
  adServiceApi: 'http://localhost:5002/api/v1',
  newAdServiceApi: 'http://localhost:5003/api/v1',
  blogServiceApi: 'http://localhost:5004/api/v1',
  cognitoUserPoolId: 'eu-west-3_lr5uwqYrJ',
  cognitoAppClientId: 'ehcgpu87ee8qplfi7ob79i13d',
  awsRegion: 'eu-west-3',
  cognitoHostedUiUrl: 'https://xoauto.auth.eu-west-3.amazoncognito.com',
  cognitoRedirectUrl: 'http://localhost:4200/success-login',
  cognitoLogoutUrl: 'http://localhost:4200/',
  CLOUD_NAME: 'dnm4rbqoc',
  API_KEY: '618589385993451',
  CURRENCY: 'TND',
};
